[build]
  functions = "netlify/functions"

[dev]
  framework = "astro"
  autoLaunch = true

[functions]
  node_bundler = "esbuild"
  # External node modules that should not be bundled
  external_node_modules = ["@netlify/blobs"] 